include_guard(GLOBAL)

if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
  set(AETHER_DEVELOPER_MODE_DEFAULT ON)
else()
  set(AETHER_DEVELOPER_MODE_DEFAULT OFF)
endif()

option(AETHER_BUILD_TESTS "Build Aether-Stream tests" ${AETHER_DEVELOPER_MODE_DEFAULT})
option(AETHER_BUILD_EXAMPLES "Build Aether-Stream examples" ${AETHER_DEVELOPER_MODE_DEFAULT})
option(AETHER_BUILD_TOOLS "Build Aether-Stream tools" ${AETHER_DEVELOPER_MODE_DEFAULT})
option(AETHER_BUILD_APPS "Build Aether-Stream CLI apps" ${AETHER_DEVELOPER_MODE_DEFAULT})
option(AETHER_BUILD_BENCHMARKS "Build Aether-Stream benchmarks" OFF)
option(AETHER_ENABLE_WARNINGS "Enable compiler warnings for Aether-Stream targets" ON)
option(AETHER_ENABLE_WARNINGS_AS_ERRORS "Treat compiler warnings as errors" OFF)
